
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'AddImageBtn': typeof import("../../components/AddImageBtn.vue")['default']
  'BusinessStories': typeof import("../../components/BusinessStories.vue")['default']
  'BusinessStoryExplorer': typeof import("../../components/BusinessStoryExplorer.vue")['default']
  'CartBtn': typeof import("../../components/CartBtn.vue")['default']
  'Checkbox': typeof import("../../components/Checkbox.vue")['default']
  'CircleProgress': typeof import("../../components/CircleProgress.vue")['default']
  'ConfirmationModal': typeof import("../../components/ConfirmationModal.vue")['default']
  'Countdown': typeof import("../../components/Countdown.vue")['default']
  'DeleteButton': typeof import("../../components/DeleteButton.vue")['default']
  'DeleteConfirmationModal': typeof import("../../components/DeleteConfirmationModal.vue")['default']
  'Dropdown': typeof import("../../components/Dropdown.vue")['default']
  'EditButton': typeof import("../../components/EditButton.vue")['default']
  'EnableDisableButton': typeof import("../../components/EnableDisableButton.vue")['default']
  'ErrorNotification': typeof import("../../components/ErrorNotification.vue")['default']
  'Explore': typeof import("../../components/Explore.vue")['default']
  'FadeTransition': typeof import("../../components/FadeTransition.vue")['default']
  'FollowButton': typeof import("../../components/FollowButton.vue")['default']
  'FollowRequests': typeof import("../../components/FollowRequests.vue")['default']
  'Home12': typeof import("../../components/Home12.vue")['default']
  'Input': typeof import("../../components/Input.vue")['default']
  'Menu': typeof import("../../components/Menu.vue")['default']
  'MobilePageHeader': typeof import("../../components/MobilePageHeader.vue")['default']
  'Modal': typeof import("../../components/Modal.vue")['default']
  'Notification': typeof import("../../components/Notification.vue")['default']
  'NuxtLogo': typeof import("../../components/NuxtLogo.vue")['default']
  'Pagination': typeof import("../../components/Pagination.vue")['default']
  'PostCreate': typeof import("../../components/PostCreate.vue")['default']
  'PriceInput': typeof import("../../components/PriceInput.vue")['default']
  'Profile12': typeof import("../../components/Profile12.vue")['default']
  'ReelUploader': typeof import("../../components/ReelUploader.vue")['default']
  'ReportModal': typeof import("../../components/ReportModal.vue")['default']
  'SearchableMultipleSelect': typeof import("../../components/SearchableMultipleSelect.vue")['default']
  'SearchableSelect': typeof import("../../components/SearchableSelect.vue")['default']
  'SlideDown': typeof import("../../components/SlideDown.vue")['default']
  'SlideOver': typeof import("../../components/SlideOver.vue")['default']
  'StoryCreate': typeof import("../../components/StoryCreate.vue")['default']
  'StoryList': typeof import("../../components/StoryList.vue")['default']
  'StoryViewer': typeof import("../../components/StoryViewer.vue")['default']
  'SubmitBtn': typeof import("../../components/SubmitBtn.vue")['default']
  'SuccessNotification': typeof import("../../components/SuccessNotification.vue")['default']
  'Table': typeof import("../../components/Table.vue")['default']
  'Tabs': typeof import("../../components/Tabs.vue")['default']
  'TagsInput': typeof import("../../components/TagsInput.vue")['default']
  'Tooltip': typeof import("../../components/Tooltip.vue")['default']
  'Tutorial': typeof import("../../components/Tutorial.vue")['default']
  'AdminAdminsForm': typeof import("../../components/admin/AdminsForm.vue")['default']
  'AdminUsersForm': typeof import("../../components/admin/UsersForm.vue")['default']
  'AdminAside': typeof import("../../components/admin/aside.vue")['default']
  'AdminBusinessesList': typeof import("../../components/admin/businesses/List.vue")['default']
  'AdminCitiesCitieslist': typeof import("../../components/admin/cities/Citieslist.vue")['default']
  'AdminCitiesCityForm': typeof import("../../components/admin/cities/CityForm.vue")['default']
  'AdminCitiesStreetForm': typeof import("../../components/admin/cities/StreetForm.vue")['default']
  'AdminCitiesStreetsList': typeof import("../../components/admin/cities/StreetsList.vue")['default']
  'AdminContactsForm': typeof import("../../components/admin/contacts/form.vue")['default']
  'AdminContactsList': typeof import("../../components/admin/contacts/list.vue")['default']
  'AdminFormsAddFieldModal': typeof import("../../components/admin/forms/AddFieldModal.vue")['default']
  'AdminFormsForm': typeof import("../../components/admin/forms/Form.vue")['default']
  'AdminGuildsForm': typeof import("../../components/admin/guilds/form.vue")['default']
  'AdminGuildsList': typeof import("../../components/admin/guilds/list.vue")['default']
  'AdminList': typeof import("../../components/admin/list.vue")['default']
  'AdminProductsForm': typeof import("../../components/admin/products/Form.vue")['default']
  'AdminProductsList': typeof import("../../components/admin/products/List.vue")['default']
  'AdminProductsRequests': typeof import("../../components/admin/products/Requests.vue")['default']
  'AdminReportsList': typeof import("../../components/admin/reports/list.vue")['default']
  'AuthenticationAvatarField': typeof import("../../components/authentication/AvatarField.vue")['default']
  'AuthenticationLoginForm': typeof import("../../components/authentication/LoginForm.vue")['default']
  'AuthenticationLoginModal': typeof import("../../components/authentication/LoginModal.vue")['default']
  'AuthenticationPasswordRecovery': typeof import("../../components/authentication/PasswordRecovery.vue")['default']
  'AuthenticationPasswordRecoveryVerifyForm': typeof import("../../components/authentication/PasswordRecoveryVerifyForm.vue")['default']
  'AuthenticationPasswordResetForm': typeof import("../../components/authentication/PasswordResetForm.vue")['default']
  'AuthenticationRegisterForm': typeof import("../../components/authentication/RegisterForm.vue")['default']
  'AuthenticationVerificationRequestForm': typeof import("../../components/authentication/VerificationRequestForm.vue")['default']
  'AuthenticationVerifyCheckForm': typeof import("../../components/authentication/VerifyCheckForm.vue")['default']
  'BusinessListItemLarge': typeof import("../../components/business/ListItemLarge.vue")['default']
  'BusinessSelectAppointment': typeof import("../../components/business/SelectAppointment.vue")['default']
  'BusinessSelectDate': typeof import("../../components/business/SelectDate.vue")['default']
  'FrontNotificationsIcon': typeof import("../../components/front/NotificationsIcon.vue")['default']
  'FrontBusinessIcons': typeof import("../../components/front/business/Icons.vue")['default']
  'FrontBusinessHeader': typeof import("../../components/front/business/header.vue")['default']
  'FrontCategoryHeader': typeof import("../../components/front/categoryHeader.vue")['default']
  'FrontComments': typeof import("../../components/front/comments.vue")['default']
  'FrontHeader': typeof import("../../components/front/header.vue")['default']
  'FrontItemPageHeader': typeof import("../../components/front/itemPageHeader.vue")['default']
  'FrontProductHeader': typeof import("../../components/front/productHeader.vue")['default']
  'FrontProductsList': typeof import("../../components/front/productsList.vue")['default']
  'Gallery': typeof import("../../components/gallery.vue")['default']
  'IconsChat2': typeof import("../../components/icons/Chat2.vue")['default']
  'IconsReport': typeof import("../../components/icons/Report.vue")['default']
  'IconsShoppingList': typeof import("../../components/icons/ShoppingList.vue")['default']
  'IconsStar': typeof import("../../components/icons/Star.vue")['default']
  'IconsCalendar': typeof import("../../components/icons/calendar.vue")['default']
  'IconsCameraPlus': typeof import("../../components/icons/cameraPlus.vue")['default']
  'IconsChat': typeof import("../../components/icons/chat.vue")['default']
  'IconsLink': typeof import("../../components/icons/link.vue")['default']
  'IconsOrders': typeof import("../../components/icons/orders.vue")['default']
  'IconsOutlineEye': typeof import("../../components/icons/outline/eye.vue")['default']
  'IconsOutlineHeart': typeof import("../../components/icons/outline/heart.vue")['default']
  'IconsOutlineSearch': typeof import("../../components/icons/outline/search.vue")['default']
  'IconsOutlineX': typeof import("../../components/icons/outline/x.vue")['default']
  'IconsReceipt': typeof import("../../components/icons/receipt.vue")['default']
  'IconsSend': typeof import("../../components/icons/send.vue")['default']
  'IconsSmile': typeof import("../../components/icons/smile.vue")['default']
  'IconsSolidChevronDown': typeof import("../../components/icons/solid/ChevronDown.vue")['default']
  'IconsSolidChevronLeft': typeof import("../../components/icons/solid/ChevronLeft.vue")['default']
  'IconsSolidChevronUp': typeof import("../../components/icons/solid/ChevronUp.vue")['default']
  'IconsSolidMapPin': typeof import("../../components/icons/solid/MapPin.vue")['default']
  'IconsSolidStar': typeof import("../../components/icons/solid/star.vue")['default']
  'PanelOrder': typeof import("../../components/panel/Order.vue")['default']
  'PanelOrdersList': typeof import("../../components/panel/OrdersList.vue")['default']
  'PanelAside': typeof import("../../components/panel/aside.vue")['default']
  'PanelBusinessAppointments': typeof import("../../components/panel/business/Appointments.vue")['default']
  'PanelBusinessCategoryProducts': typeof import("../../components/panel/business/CategoryProducts.vue")['default']
  'PanelBusinessContactInfo': typeof import("../../components/panel/business/ContactInfo.vue")['default']
  'PanelBusinessEditAddress': typeof import("../../components/panel/business/EditAddress.vue")['default']
  'PanelBusinessEditContacts': typeof import("../../components/panel/business/EditContacts.vue")['default']
  'PanelBusinessEditForm': typeof import("../../components/panel/business/EditForm.vue")['default']
  'PanelBusinessEditGallery': typeof import("../../components/panel/business/EditGallery.vue")['default']
  'PanelBusinessEditIcon': typeof import("../../components/panel/business/EditIcon.vue")['default']
  'PanelBusinessEditInfo': typeof import("../../components/panel/business/EditInfo.vue")['default']
  'PanelBusinessEditTags': typeof import("../../components/panel/business/EditTags.vue")['default']
  'PanelBusinessEditWorkTimes': typeof import("../../components/panel/business/EditWorkTimes.vue")['default']
  'PanelBusinessHolidays': typeof import("../../components/panel/business/Holidays.vue")['default']
  'PanelBusinessPriceForm': typeof import("../../components/panel/business/PriceForm.vue")['default']
  'PanelBusinessPricesTable': typeof import("../../components/panel/business/PricesTable.vue")['default']
  'PanelBusinessProductForm': typeof import("../../components/panel/business/ProductForm.vue")['default']
  'PanelBusinessRequestGeneralProducts': typeof import("../../components/panel/business/RequestGeneralProducts.vue")['default']
  'PanelBusinessSearchGeneralProducts': typeof import("../../components/panel/business/SearchGeneralProducts.vue")['default']
  'PanelBusinessCategory': typeof import("../../components/panel/business/category.vue")['default']
  'PanelBusinessList': typeof import("../../components/panel/business/list.vue")['default']
  'PanelBusinessNavigation': typeof import("../../components/panel/business/navigation.vue")['default']
  'PanelBusinessNewStep': typeof import("../../components/panel/business/new/step.vue")['default']
  'PanelChat': typeof import("../../components/panel/chat.vue")['default']
  'Popover': typeof import("../../components/popover.vue")['default']
  'Post12': typeof import("../../components/post12.vue")['default']
  'SettingP': typeof import("../../components/settingP.vue")['default']
  'Trsdfg': typeof import("../../components/trsdfg.vue")['default']
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  'LazyAddImageBtn': LazyComponent<typeof import("../../components/AddImageBtn.vue")['default']>
  'LazyBusinessStories': LazyComponent<typeof import("../../components/BusinessStories.vue")['default']>
  'LazyBusinessStoryExplorer': LazyComponent<typeof import("../../components/BusinessStoryExplorer.vue")['default']>
  'LazyCartBtn': LazyComponent<typeof import("../../components/CartBtn.vue")['default']>
  'LazyCheckbox': LazyComponent<typeof import("../../components/Checkbox.vue")['default']>
  'LazyCircleProgress': LazyComponent<typeof import("../../components/CircleProgress.vue")['default']>
  'LazyConfirmationModal': LazyComponent<typeof import("../../components/ConfirmationModal.vue")['default']>
  'LazyCountdown': LazyComponent<typeof import("../../components/Countdown.vue")['default']>
  'LazyDeleteButton': LazyComponent<typeof import("../../components/DeleteButton.vue")['default']>
  'LazyDeleteConfirmationModal': LazyComponent<typeof import("../../components/DeleteConfirmationModal.vue")['default']>
  'LazyDropdown': LazyComponent<typeof import("../../components/Dropdown.vue")['default']>
  'LazyEditButton': LazyComponent<typeof import("../../components/EditButton.vue")['default']>
  'LazyEnableDisableButton': LazyComponent<typeof import("../../components/EnableDisableButton.vue")['default']>
  'LazyErrorNotification': LazyComponent<typeof import("../../components/ErrorNotification.vue")['default']>
  'LazyExplore': LazyComponent<typeof import("../../components/Explore.vue")['default']>
  'LazyFadeTransition': LazyComponent<typeof import("../../components/FadeTransition.vue")['default']>
  'LazyFollowButton': LazyComponent<typeof import("../../components/FollowButton.vue")['default']>
  'LazyFollowRequests': LazyComponent<typeof import("../../components/FollowRequests.vue")['default']>
  'LazyHome12': LazyComponent<typeof import("../../components/Home12.vue")['default']>
  'LazyInput': LazyComponent<typeof import("../../components/Input.vue")['default']>
  'LazyMenu': LazyComponent<typeof import("../../components/Menu.vue")['default']>
  'LazyMobilePageHeader': LazyComponent<typeof import("../../components/MobilePageHeader.vue")['default']>
  'LazyModal': LazyComponent<typeof import("../../components/Modal.vue")['default']>
  'LazyNotification': LazyComponent<typeof import("../../components/Notification.vue")['default']>
  'LazyNuxtLogo': LazyComponent<typeof import("../../components/NuxtLogo.vue")['default']>
  'LazyPagination': LazyComponent<typeof import("../../components/Pagination.vue")['default']>
  'LazyPostCreate': LazyComponent<typeof import("../../components/PostCreate.vue")['default']>
  'LazyPriceInput': LazyComponent<typeof import("../../components/PriceInput.vue")['default']>
  'LazyProfile12': LazyComponent<typeof import("../../components/Profile12.vue")['default']>
  'LazyReelUploader': LazyComponent<typeof import("../../components/ReelUploader.vue")['default']>
  'LazyReportModal': LazyComponent<typeof import("../../components/ReportModal.vue")['default']>
  'LazySearchableMultipleSelect': LazyComponent<typeof import("../../components/SearchableMultipleSelect.vue")['default']>
  'LazySearchableSelect': LazyComponent<typeof import("../../components/SearchableSelect.vue")['default']>
  'LazySlideDown': LazyComponent<typeof import("../../components/SlideDown.vue")['default']>
  'LazySlideOver': LazyComponent<typeof import("../../components/SlideOver.vue")['default']>
  'LazyStoryCreate': LazyComponent<typeof import("../../components/StoryCreate.vue")['default']>
  'LazyStoryList': LazyComponent<typeof import("../../components/StoryList.vue")['default']>
  'LazyStoryViewer': LazyComponent<typeof import("../../components/StoryViewer.vue")['default']>
  'LazySubmitBtn': LazyComponent<typeof import("../../components/SubmitBtn.vue")['default']>
  'LazySuccessNotification': LazyComponent<typeof import("../../components/SuccessNotification.vue")['default']>
  'LazyTable': LazyComponent<typeof import("../../components/Table.vue")['default']>
  'LazyTabs': LazyComponent<typeof import("../../components/Tabs.vue")['default']>
  'LazyTagsInput': LazyComponent<typeof import("../../components/TagsInput.vue")['default']>
  'LazyTooltip': LazyComponent<typeof import("../../components/Tooltip.vue")['default']>
  'LazyTutorial': LazyComponent<typeof import("../../components/Tutorial.vue")['default']>
  'LazyAdminAdminsForm': LazyComponent<typeof import("../../components/admin/AdminsForm.vue")['default']>
  'LazyAdminUsersForm': LazyComponent<typeof import("../../components/admin/UsersForm.vue")['default']>
  'LazyAdminAside': LazyComponent<typeof import("../../components/admin/aside.vue")['default']>
  'LazyAdminBusinessesList': LazyComponent<typeof import("../../components/admin/businesses/List.vue")['default']>
  'LazyAdminCitiesCitieslist': LazyComponent<typeof import("../../components/admin/cities/Citieslist.vue")['default']>
  'LazyAdminCitiesCityForm': LazyComponent<typeof import("../../components/admin/cities/CityForm.vue")['default']>
  'LazyAdminCitiesStreetForm': LazyComponent<typeof import("../../components/admin/cities/StreetForm.vue")['default']>
  'LazyAdminCitiesStreetsList': LazyComponent<typeof import("../../components/admin/cities/StreetsList.vue")['default']>
  'LazyAdminContactsForm': LazyComponent<typeof import("../../components/admin/contacts/form.vue")['default']>
  'LazyAdminContactsList': LazyComponent<typeof import("../../components/admin/contacts/list.vue")['default']>
  'LazyAdminFormsAddFieldModal': LazyComponent<typeof import("../../components/admin/forms/AddFieldModal.vue")['default']>
  'LazyAdminFormsForm': LazyComponent<typeof import("../../components/admin/forms/Form.vue")['default']>
  'LazyAdminGuildsForm': LazyComponent<typeof import("../../components/admin/guilds/form.vue")['default']>
  'LazyAdminGuildsList': LazyComponent<typeof import("../../components/admin/guilds/list.vue")['default']>
  'LazyAdminList': LazyComponent<typeof import("../../components/admin/list.vue")['default']>
  'LazyAdminProductsForm': LazyComponent<typeof import("../../components/admin/products/Form.vue")['default']>
  'LazyAdminProductsList': LazyComponent<typeof import("../../components/admin/products/List.vue")['default']>
  'LazyAdminProductsRequests': LazyComponent<typeof import("../../components/admin/products/Requests.vue")['default']>
  'LazyAdminReportsList': LazyComponent<typeof import("../../components/admin/reports/list.vue")['default']>
  'LazyAuthenticationAvatarField': LazyComponent<typeof import("../../components/authentication/AvatarField.vue")['default']>
  'LazyAuthenticationLoginForm': LazyComponent<typeof import("../../components/authentication/LoginForm.vue")['default']>
  'LazyAuthenticationLoginModal': LazyComponent<typeof import("../../components/authentication/LoginModal.vue")['default']>
  'LazyAuthenticationPasswordRecovery': LazyComponent<typeof import("../../components/authentication/PasswordRecovery.vue")['default']>
  'LazyAuthenticationPasswordRecoveryVerifyForm': LazyComponent<typeof import("../../components/authentication/PasswordRecoveryVerifyForm.vue")['default']>
  'LazyAuthenticationPasswordResetForm': LazyComponent<typeof import("../../components/authentication/PasswordResetForm.vue")['default']>
  'LazyAuthenticationRegisterForm': LazyComponent<typeof import("../../components/authentication/RegisterForm.vue")['default']>
  'LazyAuthenticationVerificationRequestForm': LazyComponent<typeof import("../../components/authentication/VerificationRequestForm.vue")['default']>
  'LazyAuthenticationVerifyCheckForm': LazyComponent<typeof import("../../components/authentication/VerifyCheckForm.vue")['default']>
  'LazyBusinessListItemLarge': LazyComponent<typeof import("../../components/business/ListItemLarge.vue")['default']>
  'LazyBusinessSelectAppointment': LazyComponent<typeof import("../../components/business/SelectAppointment.vue")['default']>
  'LazyBusinessSelectDate': LazyComponent<typeof import("../../components/business/SelectDate.vue")['default']>
  'LazyFrontNotificationsIcon': LazyComponent<typeof import("../../components/front/NotificationsIcon.vue")['default']>
  'LazyFrontBusinessIcons': LazyComponent<typeof import("../../components/front/business/Icons.vue")['default']>
  'LazyFrontBusinessHeader': LazyComponent<typeof import("../../components/front/business/header.vue")['default']>
  'LazyFrontCategoryHeader': LazyComponent<typeof import("../../components/front/categoryHeader.vue")['default']>
  'LazyFrontComments': LazyComponent<typeof import("../../components/front/comments.vue")['default']>
  'LazyFrontHeader': LazyComponent<typeof import("../../components/front/header.vue")['default']>
  'LazyFrontItemPageHeader': LazyComponent<typeof import("../../components/front/itemPageHeader.vue")['default']>
  'LazyFrontProductHeader': LazyComponent<typeof import("../../components/front/productHeader.vue")['default']>
  'LazyFrontProductsList': LazyComponent<typeof import("../../components/front/productsList.vue")['default']>
  'LazyGallery': LazyComponent<typeof import("../../components/gallery.vue")['default']>
  'LazyIconsChat2': LazyComponent<typeof import("../../components/icons/Chat2.vue")['default']>
  'LazyIconsReport': LazyComponent<typeof import("../../components/icons/Report.vue")['default']>
  'LazyIconsShoppingList': LazyComponent<typeof import("../../components/icons/ShoppingList.vue")['default']>
  'LazyIconsStar': LazyComponent<typeof import("../../components/icons/Star.vue")['default']>
  'LazyIconsCalendar': LazyComponent<typeof import("../../components/icons/calendar.vue")['default']>
  'LazyIconsCameraPlus': LazyComponent<typeof import("../../components/icons/cameraPlus.vue")['default']>
  'LazyIconsChat': LazyComponent<typeof import("../../components/icons/chat.vue")['default']>
  'LazyIconsLink': LazyComponent<typeof import("../../components/icons/link.vue")['default']>
  'LazyIconsOrders': LazyComponent<typeof import("../../components/icons/orders.vue")['default']>
  'LazyIconsOutlineEye': LazyComponent<typeof import("../../components/icons/outline/eye.vue")['default']>
  'LazyIconsOutlineHeart': LazyComponent<typeof import("../../components/icons/outline/heart.vue")['default']>
  'LazyIconsOutlineSearch': LazyComponent<typeof import("../../components/icons/outline/search.vue")['default']>
  'LazyIconsOutlineX': LazyComponent<typeof import("../../components/icons/outline/x.vue")['default']>
  'LazyIconsReceipt': LazyComponent<typeof import("../../components/icons/receipt.vue")['default']>
  'LazyIconsSend': LazyComponent<typeof import("../../components/icons/send.vue")['default']>
  'LazyIconsSmile': LazyComponent<typeof import("../../components/icons/smile.vue")['default']>
  'LazyIconsSolidChevronDown': LazyComponent<typeof import("../../components/icons/solid/ChevronDown.vue")['default']>
  'LazyIconsSolidChevronLeft': LazyComponent<typeof import("../../components/icons/solid/ChevronLeft.vue")['default']>
  'LazyIconsSolidChevronUp': LazyComponent<typeof import("../../components/icons/solid/ChevronUp.vue")['default']>
  'LazyIconsSolidMapPin': LazyComponent<typeof import("../../components/icons/solid/MapPin.vue")['default']>
  'LazyIconsSolidStar': LazyComponent<typeof import("../../components/icons/solid/star.vue")['default']>
  'LazyPanelOrder': LazyComponent<typeof import("../../components/panel/Order.vue")['default']>
  'LazyPanelOrdersList': LazyComponent<typeof import("../../components/panel/OrdersList.vue")['default']>
  'LazyPanelAside': LazyComponent<typeof import("../../components/panel/aside.vue")['default']>
  'LazyPanelBusinessAppointments': LazyComponent<typeof import("../../components/panel/business/Appointments.vue")['default']>
  'LazyPanelBusinessCategoryProducts': LazyComponent<typeof import("../../components/panel/business/CategoryProducts.vue")['default']>
  'LazyPanelBusinessContactInfo': LazyComponent<typeof import("../../components/panel/business/ContactInfo.vue")['default']>
  'LazyPanelBusinessEditAddress': LazyComponent<typeof import("../../components/panel/business/EditAddress.vue")['default']>
  'LazyPanelBusinessEditContacts': LazyComponent<typeof import("../../components/panel/business/EditContacts.vue")['default']>
  'LazyPanelBusinessEditForm': LazyComponent<typeof import("../../components/panel/business/EditForm.vue")['default']>
  'LazyPanelBusinessEditGallery': LazyComponent<typeof import("../../components/panel/business/EditGallery.vue")['default']>
  'LazyPanelBusinessEditIcon': LazyComponent<typeof import("../../components/panel/business/EditIcon.vue")['default']>
  'LazyPanelBusinessEditInfo': LazyComponent<typeof import("../../components/panel/business/EditInfo.vue")['default']>
  'LazyPanelBusinessEditTags': LazyComponent<typeof import("../../components/panel/business/EditTags.vue")['default']>
  'LazyPanelBusinessEditWorkTimes': LazyComponent<typeof import("../../components/panel/business/EditWorkTimes.vue")['default']>
  'LazyPanelBusinessHolidays': LazyComponent<typeof import("../../components/panel/business/Holidays.vue")['default']>
  'LazyPanelBusinessPriceForm': LazyComponent<typeof import("../../components/panel/business/PriceForm.vue")['default']>
  'LazyPanelBusinessPricesTable': LazyComponent<typeof import("../../components/panel/business/PricesTable.vue")['default']>
  'LazyPanelBusinessProductForm': LazyComponent<typeof import("../../components/panel/business/ProductForm.vue")['default']>
  'LazyPanelBusinessRequestGeneralProducts': LazyComponent<typeof import("../../components/panel/business/RequestGeneralProducts.vue")['default']>
  'LazyPanelBusinessSearchGeneralProducts': LazyComponent<typeof import("../../components/panel/business/SearchGeneralProducts.vue")['default']>
  'LazyPanelBusinessCategory': LazyComponent<typeof import("../../components/panel/business/category.vue")['default']>
  'LazyPanelBusinessList': LazyComponent<typeof import("../../components/panel/business/list.vue")['default']>
  'LazyPanelBusinessNavigation': LazyComponent<typeof import("../../components/panel/business/navigation.vue")['default']>
  'LazyPanelBusinessNewStep': LazyComponent<typeof import("../../components/panel/business/new/step.vue")['default']>
  'LazyPanelChat': LazyComponent<typeof import("../../components/panel/chat.vue")['default']>
  'LazyPopover': LazyComponent<typeof import("../../components/popover.vue")['default']>
  'LazyPost12': LazyComponent<typeof import("../../components/post12.vue")['default']>
  'LazySettingP': LazyComponent<typeof import("../../components/settingP.vue")['default']>
  'LazyTrsdfg': LazyComponent<typeof import("../../components/trsdfg.vue")['default']>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
