// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/12/2025, 1:39:10 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["D:/bazar/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/bazar/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/bazar/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/bazar/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/bazar/plugins/**/*.{js,ts,mjs}","D:/bazar/composables/**/*.{js,ts,mjs}","D:/bazar/utils/**/*.{js,ts,mjs}","D:/bazar/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/bazar/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/bazar/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/bazar/app.config.{js,ts,mjs}","D:/bazar/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;