
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AddImageBtn: typeof import("../components/AddImageBtn.vue")['default']
export const BusinessStories: typeof import("../components/BusinessStories.vue")['default']
export const BusinessStoryExplorer: typeof import("../components/BusinessStoryExplorer.vue")['default']
export const CartBtn: typeof import("../components/CartBtn.vue")['default']
export const Checkbox: typeof import("../components/Checkbox.vue")['default']
export const CircleProgress: typeof import("../components/CircleProgress.vue")['default']
export const ConfirmationModal: typeof import("../components/ConfirmationModal.vue")['default']
export const Countdown: typeof import("../components/Countdown.vue")['default']
export const DeleteButton: typeof import("../components/DeleteButton.vue")['default']
export const DeleteConfirmationModal: typeof import("../components/DeleteConfirmationModal.vue")['default']
export const Dropdown: typeof import("../components/Dropdown.vue")['default']
export const EditButton: typeof import("../components/EditButton.vue")['default']
export const EnableDisableButton: typeof import("../components/EnableDisableButton.vue")['default']
export const ErrorNotification: typeof import("../components/ErrorNotification.vue")['default']
export const Explore: typeof import("../components/Explore.vue")['default']
export const FadeTransition: typeof import("../components/FadeTransition.vue")['default']
export const FollowButton: typeof import("../components/FollowButton.vue")['default']
export const FollowRequests: typeof import("../components/FollowRequests.vue")['default']
export const Home12: typeof import("../components/Home12.vue")['default']
export const Input: typeof import("../components/Input.vue")['default']
export const Menu: typeof import("../components/Menu.vue")['default']
export const MobilePageHeader: typeof import("../components/MobilePageHeader.vue")['default']
export const Modal: typeof import("../components/Modal.vue")['default']
export const Notification: typeof import("../components/Notification.vue")['default']
export const NuxtLogo: typeof import("../components/NuxtLogo.vue")['default']
export const Pagination: typeof import("../components/Pagination.vue")['default']
export const PostCreate: typeof import("../components/PostCreate.vue")['default']
export const PriceInput: typeof import("../components/PriceInput.vue")['default']
export const Profile12: typeof import("../components/Profile12.vue")['default']
export const ReelUploader: typeof import("../components/ReelUploader.vue")['default']
export const ReportModal: typeof import("../components/ReportModal.vue")['default']
export const SearchableMultipleSelect: typeof import("../components/SearchableMultipleSelect.vue")['default']
export const SearchableSelect: typeof import("../components/SearchableSelect.vue")['default']
export const SlideDown: typeof import("../components/SlideDown.vue")['default']
export const SlideOver: typeof import("../components/SlideOver.vue")['default']
export const StoryCreate: typeof import("../components/StoryCreate.vue")['default']
export const StoryList: typeof import("../components/StoryList.vue")['default']
export const StoryViewer: typeof import("../components/StoryViewer.vue")['default']
export const SubmitBtn: typeof import("../components/SubmitBtn.vue")['default']
export const SuccessNotification: typeof import("../components/SuccessNotification.vue")['default']
export const Table: typeof import("../components/Table.vue")['default']
export const Tabs: typeof import("../components/Tabs.vue")['default']
export const TagsInput: typeof import("../components/TagsInput.vue")['default']
export const Tooltip: typeof import("../components/Tooltip.vue")['default']
export const Tutorial: typeof import("../components/Tutorial.vue")['default']
export const AdminAdminsForm: typeof import("../components/admin/AdminsForm.vue")['default']
export const AdminUsersForm: typeof import("../components/admin/UsersForm.vue")['default']
export const AdminAside: typeof import("../components/admin/aside.vue")['default']
export const AdminBusinessesList: typeof import("../components/admin/businesses/List.vue")['default']
export const AdminCitiesCitieslist: typeof import("../components/admin/cities/Citieslist.vue")['default']
export const AdminCitiesCityForm: typeof import("../components/admin/cities/CityForm.vue")['default']
export const AdminCitiesStreetForm: typeof import("../components/admin/cities/StreetForm.vue")['default']
export const AdminCitiesStreetsList: typeof import("../components/admin/cities/StreetsList.vue")['default']
export const AdminContactsForm: typeof import("../components/admin/contacts/form.vue")['default']
export const AdminContactsList: typeof import("../components/admin/contacts/list.vue")['default']
export const AdminFormsAddFieldModal: typeof import("../components/admin/forms/AddFieldModal.vue")['default']
export const AdminFormsForm: typeof import("../components/admin/forms/Form.vue")['default']
export const AdminGuildsForm: typeof import("../components/admin/guilds/form.vue")['default']
export const AdminGuildsList: typeof import("../components/admin/guilds/list.vue")['default']
export const AdminList: typeof import("../components/admin/list.vue")['default']
export const AdminProductsForm: typeof import("../components/admin/products/Form.vue")['default']
export const AdminProductsList: typeof import("../components/admin/products/List.vue")['default']
export const AdminProductsRequests: typeof import("../components/admin/products/Requests.vue")['default']
export const AdminReportsList: typeof import("../components/admin/reports/list.vue")['default']
export const AuthenticationAvatarField: typeof import("../components/authentication/AvatarField.vue")['default']
export const AuthenticationLoginForm: typeof import("../components/authentication/LoginForm.vue")['default']
export const AuthenticationLoginModal: typeof import("../components/authentication/LoginModal.vue")['default']
export const AuthenticationPasswordRecovery: typeof import("../components/authentication/PasswordRecovery.vue")['default']
export const AuthenticationPasswordRecoveryVerifyForm: typeof import("../components/authentication/PasswordRecoveryVerifyForm.vue")['default']
export const AuthenticationPasswordResetForm: typeof import("../components/authentication/PasswordResetForm.vue")['default']
export const AuthenticationRegisterForm: typeof import("../components/authentication/RegisterForm.vue")['default']
export const AuthenticationVerificationRequestForm: typeof import("../components/authentication/VerificationRequestForm.vue")['default']
export const AuthenticationVerifyCheckForm: typeof import("../components/authentication/VerifyCheckForm.vue")['default']
export const BusinessListItemLarge: typeof import("../components/business/ListItemLarge.vue")['default']
export const BusinessSelectAppointment: typeof import("../components/business/SelectAppointment.vue")['default']
export const BusinessSelectDate: typeof import("../components/business/SelectDate.vue")['default']
export const FrontNotificationsIcon: typeof import("../components/front/NotificationsIcon.vue")['default']
export const FrontBusinessIcons: typeof import("../components/front/business/Icons.vue")['default']
export const FrontBusinessHeader: typeof import("../components/front/business/header.vue")['default']
export const FrontCategoryHeader: typeof import("../components/front/categoryHeader.vue")['default']
export const FrontComments: typeof import("../components/front/comments.vue")['default']
export const FrontHeader: typeof import("../components/front/header.vue")['default']
export const FrontItemPageHeader: typeof import("../components/front/itemPageHeader.vue")['default']
export const FrontProductHeader: typeof import("../components/front/productHeader.vue")['default']
export const FrontProductsList: typeof import("../components/front/productsList.vue")['default']
export const Gallery: typeof import("../components/gallery.vue")['default']
export const IconsChat2: typeof import("../components/icons/Chat2.vue")['default']
export const IconsReport: typeof import("../components/icons/Report.vue")['default']
export const IconsShoppingList: typeof import("../components/icons/ShoppingList.vue")['default']
export const IconsStar: typeof import("../components/icons/Star.vue")['default']
export const IconsCalendar: typeof import("../components/icons/calendar.vue")['default']
export const IconsCameraPlus: typeof import("../components/icons/cameraPlus.vue")['default']
export const IconsChat: typeof import("../components/icons/chat.vue")['default']
export const IconsLink: typeof import("../components/icons/link.vue")['default']
export const IconsOrders: typeof import("../components/icons/orders.vue")['default']
export const IconsOutlineEye: typeof import("../components/icons/outline/eye.vue")['default']
export const IconsOutlineHeart: typeof import("../components/icons/outline/heart.vue")['default']
export const IconsOutlineSearch: typeof import("../components/icons/outline/search.vue")['default']
export const IconsOutlineX: typeof import("../components/icons/outline/x.vue")['default']
export const IconsReceipt: typeof import("../components/icons/receipt.vue")['default']
export const IconsSend: typeof import("../components/icons/send.vue")['default']
export const IconsSmile: typeof import("../components/icons/smile.vue")['default']
export const IconsSolidChevronDown: typeof import("../components/icons/solid/ChevronDown.vue")['default']
export const IconsSolidChevronLeft: typeof import("../components/icons/solid/ChevronLeft.vue")['default']
export const IconsSolidChevronUp: typeof import("../components/icons/solid/ChevronUp.vue")['default']
export const IconsSolidMapPin: typeof import("../components/icons/solid/MapPin.vue")['default']
export const IconsSolidStar: typeof import("../components/icons/solid/star.vue")['default']
export const PanelOrder: typeof import("../components/panel/Order.vue")['default']
export const PanelOrdersList: typeof import("../components/panel/OrdersList.vue")['default']
export const PanelAside: typeof import("../components/panel/aside.vue")['default']
export const PanelBusinessAppointments: typeof import("../components/panel/business/Appointments.vue")['default']
export const PanelBusinessCategoryProducts: typeof import("../components/panel/business/CategoryProducts.vue")['default']
export const PanelBusinessContactInfo: typeof import("../components/panel/business/ContactInfo.vue")['default']
export const PanelBusinessEditAddress: typeof import("../components/panel/business/EditAddress.vue")['default']
export const PanelBusinessEditContacts: typeof import("../components/panel/business/EditContacts.vue")['default']
export const PanelBusinessEditForm: typeof import("../components/panel/business/EditForm.vue")['default']
export const PanelBusinessEditGallery: typeof import("../components/panel/business/EditGallery.vue")['default']
export const PanelBusinessEditIcon: typeof import("../components/panel/business/EditIcon.vue")['default']
export const PanelBusinessEditInfo: typeof import("../components/panel/business/EditInfo.vue")['default']
export const PanelBusinessEditTags: typeof import("../components/panel/business/EditTags.vue")['default']
export const PanelBusinessEditWorkTimes: typeof import("../components/panel/business/EditWorkTimes.vue")['default']
export const PanelBusinessHolidays: typeof import("../components/panel/business/Holidays.vue")['default']
export const PanelBusinessPriceForm: typeof import("../components/panel/business/PriceForm.vue")['default']
export const PanelBusinessPricesTable: typeof import("../components/panel/business/PricesTable.vue")['default']
export const PanelBusinessProductForm: typeof import("../components/panel/business/ProductForm.vue")['default']
export const PanelBusinessRequestGeneralProducts: typeof import("../components/panel/business/RequestGeneralProducts.vue")['default']
export const PanelBusinessSearchGeneralProducts: typeof import("../components/panel/business/SearchGeneralProducts.vue")['default']
export const PanelBusinessCategory: typeof import("../components/panel/business/category.vue")['default']
export const PanelBusinessList: typeof import("../components/panel/business/list.vue")['default']
export const PanelBusinessNavigation: typeof import("../components/panel/business/navigation.vue")['default']
export const PanelBusinessNewStep: typeof import("../components/panel/business/new/step.vue")['default']
export const PanelChat: typeof import("../components/panel/chat.vue")['default']
export const Popover: typeof import("../components/popover.vue")['default']
export const Post12: typeof import("../components/post12.vue")['default']
export const SettingP: typeof import("../components/settingP.vue")['default']
export const Trsdfg: typeof import("../components/trsdfg.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAddImageBtn: LazyComponent<typeof import("../components/AddImageBtn.vue")['default']>
export const LazyBusinessStories: LazyComponent<typeof import("../components/BusinessStories.vue")['default']>
export const LazyBusinessStoryExplorer: LazyComponent<typeof import("../components/BusinessStoryExplorer.vue")['default']>
export const LazyCartBtn: LazyComponent<typeof import("../components/CartBtn.vue")['default']>
export const LazyCheckbox: LazyComponent<typeof import("../components/Checkbox.vue")['default']>
export const LazyCircleProgress: LazyComponent<typeof import("../components/CircleProgress.vue")['default']>
export const LazyConfirmationModal: LazyComponent<typeof import("../components/ConfirmationModal.vue")['default']>
export const LazyCountdown: LazyComponent<typeof import("../components/Countdown.vue")['default']>
export const LazyDeleteButton: LazyComponent<typeof import("../components/DeleteButton.vue")['default']>
export const LazyDeleteConfirmationModal: LazyComponent<typeof import("../components/DeleteConfirmationModal.vue")['default']>
export const LazyDropdown: LazyComponent<typeof import("../components/Dropdown.vue")['default']>
export const LazyEditButton: LazyComponent<typeof import("../components/EditButton.vue")['default']>
export const LazyEnableDisableButton: LazyComponent<typeof import("../components/EnableDisableButton.vue")['default']>
export const LazyErrorNotification: LazyComponent<typeof import("../components/ErrorNotification.vue")['default']>
export const LazyExplore: LazyComponent<typeof import("../components/Explore.vue")['default']>
export const LazyFadeTransition: LazyComponent<typeof import("../components/FadeTransition.vue")['default']>
export const LazyFollowButton: LazyComponent<typeof import("../components/FollowButton.vue")['default']>
export const LazyFollowRequests: LazyComponent<typeof import("../components/FollowRequests.vue")['default']>
export const LazyHome12: LazyComponent<typeof import("../components/Home12.vue")['default']>
export const LazyInput: LazyComponent<typeof import("../components/Input.vue")['default']>
export const LazyMenu: LazyComponent<typeof import("../components/Menu.vue")['default']>
export const LazyMobilePageHeader: LazyComponent<typeof import("../components/MobilePageHeader.vue")['default']>
export const LazyModal: LazyComponent<typeof import("../components/Modal.vue")['default']>
export const LazyNotification: LazyComponent<typeof import("../components/Notification.vue")['default']>
export const LazyNuxtLogo: LazyComponent<typeof import("../components/NuxtLogo.vue")['default']>
export const LazyPagination: LazyComponent<typeof import("../components/Pagination.vue")['default']>
export const LazyPostCreate: LazyComponent<typeof import("../components/PostCreate.vue")['default']>
export const LazyPriceInput: LazyComponent<typeof import("../components/PriceInput.vue")['default']>
export const LazyProfile12: LazyComponent<typeof import("../components/Profile12.vue")['default']>
export const LazyReelUploader: LazyComponent<typeof import("../components/ReelUploader.vue")['default']>
export const LazyReportModal: LazyComponent<typeof import("../components/ReportModal.vue")['default']>
export const LazySearchableMultipleSelect: LazyComponent<typeof import("../components/SearchableMultipleSelect.vue")['default']>
export const LazySearchableSelect: LazyComponent<typeof import("../components/SearchableSelect.vue")['default']>
export const LazySlideDown: LazyComponent<typeof import("../components/SlideDown.vue")['default']>
export const LazySlideOver: LazyComponent<typeof import("../components/SlideOver.vue")['default']>
export const LazyStoryCreate: LazyComponent<typeof import("../components/StoryCreate.vue")['default']>
export const LazyStoryList: LazyComponent<typeof import("../components/StoryList.vue")['default']>
export const LazyStoryViewer: LazyComponent<typeof import("../components/StoryViewer.vue")['default']>
export const LazySubmitBtn: LazyComponent<typeof import("../components/SubmitBtn.vue")['default']>
export const LazySuccessNotification: LazyComponent<typeof import("../components/SuccessNotification.vue")['default']>
export const LazyTable: LazyComponent<typeof import("../components/Table.vue")['default']>
export const LazyTabs: LazyComponent<typeof import("../components/Tabs.vue")['default']>
export const LazyTagsInput: LazyComponent<typeof import("../components/TagsInput.vue")['default']>
export const LazyTooltip: LazyComponent<typeof import("../components/Tooltip.vue")['default']>
export const LazyTutorial: LazyComponent<typeof import("../components/Tutorial.vue")['default']>
export const LazyAdminAdminsForm: LazyComponent<typeof import("../components/admin/AdminsForm.vue")['default']>
export const LazyAdminUsersForm: LazyComponent<typeof import("../components/admin/UsersForm.vue")['default']>
export const LazyAdminAside: LazyComponent<typeof import("../components/admin/aside.vue")['default']>
export const LazyAdminBusinessesList: LazyComponent<typeof import("../components/admin/businesses/List.vue")['default']>
export const LazyAdminCitiesCitieslist: LazyComponent<typeof import("../components/admin/cities/Citieslist.vue")['default']>
export const LazyAdminCitiesCityForm: LazyComponent<typeof import("../components/admin/cities/CityForm.vue")['default']>
export const LazyAdminCitiesStreetForm: LazyComponent<typeof import("../components/admin/cities/StreetForm.vue")['default']>
export const LazyAdminCitiesStreetsList: LazyComponent<typeof import("../components/admin/cities/StreetsList.vue")['default']>
export const LazyAdminContactsForm: LazyComponent<typeof import("../components/admin/contacts/form.vue")['default']>
export const LazyAdminContactsList: LazyComponent<typeof import("../components/admin/contacts/list.vue")['default']>
export const LazyAdminFormsAddFieldModal: LazyComponent<typeof import("../components/admin/forms/AddFieldModal.vue")['default']>
export const LazyAdminFormsForm: LazyComponent<typeof import("../components/admin/forms/Form.vue")['default']>
export const LazyAdminGuildsForm: LazyComponent<typeof import("../components/admin/guilds/form.vue")['default']>
export const LazyAdminGuildsList: LazyComponent<typeof import("../components/admin/guilds/list.vue")['default']>
export const LazyAdminList: LazyComponent<typeof import("../components/admin/list.vue")['default']>
export const LazyAdminProductsForm: LazyComponent<typeof import("../components/admin/products/Form.vue")['default']>
export const LazyAdminProductsList: LazyComponent<typeof import("../components/admin/products/List.vue")['default']>
export const LazyAdminProductsRequests: LazyComponent<typeof import("../components/admin/products/Requests.vue")['default']>
export const LazyAdminReportsList: LazyComponent<typeof import("../components/admin/reports/list.vue")['default']>
export const LazyAuthenticationAvatarField: LazyComponent<typeof import("../components/authentication/AvatarField.vue")['default']>
export const LazyAuthenticationLoginForm: LazyComponent<typeof import("../components/authentication/LoginForm.vue")['default']>
export const LazyAuthenticationLoginModal: LazyComponent<typeof import("../components/authentication/LoginModal.vue")['default']>
export const LazyAuthenticationPasswordRecovery: LazyComponent<typeof import("../components/authentication/PasswordRecovery.vue")['default']>
export const LazyAuthenticationPasswordRecoveryVerifyForm: LazyComponent<typeof import("../components/authentication/PasswordRecoveryVerifyForm.vue")['default']>
export const LazyAuthenticationPasswordResetForm: LazyComponent<typeof import("../components/authentication/PasswordResetForm.vue")['default']>
export const LazyAuthenticationRegisterForm: LazyComponent<typeof import("../components/authentication/RegisterForm.vue")['default']>
export const LazyAuthenticationVerificationRequestForm: LazyComponent<typeof import("../components/authentication/VerificationRequestForm.vue")['default']>
export const LazyAuthenticationVerifyCheckForm: LazyComponent<typeof import("../components/authentication/VerifyCheckForm.vue")['default']>
export const LazyBusinessListItemLarge: LazyComponent<typeof import("../components/business/ListItemLarge.vue")['default']>
export const LazyBusinessSelectAppointment: LazyComponent<typeof import("../components/business/SelectAppointment.vue")['default']>
export const LazyBusinessSelectDate: LazyComponent<typeof import("../components/business/SelectDate.vue")['default']>
export const LazyFrontNotificationsIcon: LazyComponent<typeof import("../components/front/NotificationsIcon.vue")['default']>
export const LazyFrontBusinessIcons: LazyComponent<typeof import("../components/front/business/Icons.vue")['default']>
export const LazyFrontBusinessHeader: LazyComponent<typeof import("../components/front/business/header.vue")['default']>
export const LazyFrontCategoryHeader: LazyComponent<typeof import("../components/front/categoryHeader.vue")['default']>
export const LazyFrontComments: LazyComponent<typeof import("../components/front/comments.vue")['default']>
export const LazyFrontHeader: LazyComponent<typeof import("../components/front/header.vue")['default']>
export const LazyFrontItemPageHeader: LazyComponent<typeof import("../components/front/itemPageHeader.vue")['default']>
export const LazyFrontProductHeader: LazyComponent<typeof import("../components/front/productHeader.vue")['default']>
export const LazyFrontProductsList: LazyComponent<typeof import("../components/front/productsList.vue")['default']>
export const LazyGallery: LazyComponent<typeof import("../components/gallery.vue")['default']>
export const LazyIconsChat2: LazyComponent<typeof import("../components/icons/Chat2.vue")['default']>
export const LazyIconsReport: LazyComponent<typeof import("../components/icons/Report.vue")['default']>
export const LazyIconsShoppingList: LazyComponent<typeof import("../components/icons/ShoppingList.vue")['default']>
export const LazyIconsStar: LazyComponent<typeof import("../components/icons/Star.vue")['default']>
export const LazyIconsCalendar: LazyComponent<typeof import("../components/icons/calendar.vue")['default']>
export const LazyIconsCameraPlus: LazyComponent<typeof import("../components/icons/cameraPlus.vue")['default']>
export const LazyIconsChat: LazyComponent<typeof import("../components/icons/chat.vue")['default']>
export const LazyIconsLink: LazyComponent<typeof import("../components/icons/link.vue")['default']>
export const LazyIconsOrders: LazyComponent<typeof import("../components/icons/orders.vue")['default']>
export const LazyIconsOutlineEye: LazyComponent<typeof import("../components/icons/outline/eye.vue")['default']>
export const LazyIconsOutlineHeart: LazyComponent<typeof import("../components/icons/outline/heart.vue")['default']>
export const LazyIconsOutlineSearch: LazyComponent<typeof import("../components/icons/outline/search.vue")['default']>
export const LazyIconsOutlineX: LazyComponent<typeof import("../components/icons/outline/x.vue")['default']>
export const LazyIconsReceipt: LazyComponent<typeof import("../components/icons/receipt.vue")['default']>
export const LazyIconsSend: LazyComponent<typeof import("../components/icons/send.vue")['default']>
export const LazyIconsSmile: LazyComponent<typeof import("../components/icons/smile.vue")['default']>
export const LazyIconsSolidChevronDown: LazyComponent<typeof import("../components/icons/solid/ChevronDown.vue")['default']>
export const LazyIconsSolidChevronLeft: LazyComponent<typeof import("../components/icons/solid/ChevronLeft.vue")['default']>
export const LazyIconsSolidChevronUp: LazyComponent<typeof import("../components/icons/solid/ChevronUp.vue")['default']>
export const LazyIconsSolidMapPin: LazyComponent<typeof import("../components/icons/solid/MapPin.vue")['default']>
export const LazyIconsSolidStar: LazyComponent<typeof import("../components/icons/solid/star.vue")['default']>
export const LazyPanelOrder: LazyComponent<typeof import("../components/panel/Order.vue")['default']>
export const LazyPanelOrdersList: LazyComponent<typeof import("../components/panel/OrdersList.vue")['default']>
export const LazyPanelAside: LazyComponent<typeof import("../components/panel/aside.vue")['default']>
export const LazyPanelBusinessAppointments: LazyComponent<typeof import("../components/panel/business/Appointments.vue")['default']>
export const LazyPanelBusinessCategoryProducts: LazyComponent<typeof import("../components/panel/business/CategoryProducts.vue")['default']>
export const LazyPanelBusinessContactInfo: LazyComponent<typeof import("../components/panel/business/ContactInfo.vue")['default']>
export const LazyPanelBusinessEditAddress: LazyComponent<typeof import("../components/panel/business/EditAddress.vue")['default']>
export const LazyPanelBusinessEditContacts: LazyComponent<typeof import("../components/panel/business/EditContacts.vue")['default']>
export const LazyPanelBusinessEditForm: LazyComponent<typeof import("../components/panel/business/EditForm.vue")['default']>
export const LazyPanelBusinessEditGallery: LazyComponent<typeof import("../components/panel/business/EditGallery.vue")['default']>
export const LazyPanelBusinessEditIcon: LazyComponent<typeof import("../components/panel/business/EditIcon.vue")['default']>
export const LazyPanelBusinessEditInfo: LazyComponent<typeof import("../components/panel/business/EditInfo.vue")['default']>
export const LazyPanelBusinessEditTags: LazyComponent<typeof import("../components/panel/business/EditTags.vue")['default']>
export const LazyPanelBusinessEditWorkTimes: LazyComponent<typeof import("../components/panel/business/EditWorkTimes.vue")['default']>
export const LazyPanelBusinessHolidays: LazyComponent<typeof import("../components/panel/business/Holidays.vue")['default']>
export const LazyPanelBusinessPriceForm: LazyComponent<typeof import("../components/panel/business/PriceForm.vue")['default']>
export const LazyPanelBusinessPricesTable: LazyComponent<typeof import("../components/panel/business/PricesTable.vue")['default']>
export const LazyPanelBusinessProductForm: LazyComponent<typeof import("../components/panel/business/ProductForm.vue")['default']>
export const LazyPanelBusinessRequestGeneralProducts: LazyComponent<typeof import("../components/panel/business/RequestGeneralProducts.vue")['default']>
export const LazyPanelBusinessSearchGeneralProducts: LazyComponent<typeof import("../components/panel/business/SearchGeneralProducts.vue")['default']>
export const LazyPanelBusinessCategory: LazyComponent<typeof import("../components/panel/business/category.vue")['default']>
export const LazyPanelBusinessList: LazyComponent<typeof import("../components/panel/business/list.vue")['default']>
export const LazyPanelBusinessNavigation: LazyComponent<typeof import("../components/panel/business/navigation.vue")['default']>
export const LazyPanelBusinessNewStep: LazyComponent<typeof import("../components/panel/business/new/step.vue")['default']>
export const LazyPanelChat: LazyComponent<typeof import("../components/panel/chat.vue")['default']>
export const LazyPopover: LazyComponent<typeof import("../components/popover.vue")['default']>
export const LazyPost12: LazyComponent<typeof import("../components/post12.vue")['default']>
export const LazySettingP: LazyComponent<typeof import("../components/settingP.vue")['default']>
export const LazyTrsdfg: LazyComponent<typeof import("../components/trsdfg.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
